services:
  - type: web
    name: forum-app-backend
    env: node
    region: frankfurt
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend-url.onrender.com

  - type: web
    name: forum-app-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: NODE_ENV
        value: production 