name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install client dependencies
        working-directory: ./client
        run: |
          npm ci
          npm install gh-pages --save-dev

      - name: Update homepage in package.json
        working-directory: ./client
        run: |
          node -e "const pkg=require('./package.json'); pkg.homepage='https://onurguvensoy.github.io/forum-app'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2))"

      - name: Build client
        working-directory: ./client
        run: |
          CI=false npm run build
          cp build/index.html build/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: client/build
          branch: gh-pages
          clean: true 